clean:
	rm ./obj/1.o
	rm ./obj/2.o
	rm ./obj/3.o


#	@echo "\n#Compilação dos TADS (Tipos abstratos de dados)..."
#	@echo "\n#Excluindo os programas (executáveis) e os arquivos intermediários..."
#	@echo "\n#Compilação dos Aplicativos (Executáveis)..."